CREATE TABLE IF NOT EXISTS backtest_runs (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  strategy_id TEXT NOT NULL,
  strategy_version INTEGER NOT NULL,
  status TEXT NOT NULL,
  market TEXT NOT NULL,
  start_date TEXT NOT NULL,
  end_date TEXT NOT NULL,
  initial_capital REAL NOT NULL,
  benchmark TEXT,
  commission_rate REAL,
  slippage_bps REAL,
  result_r2_key TEXT,
  total_return REAL,
  annualized_return REAL,
  sharpe_ratio REAL,
  max_drawdown REAL,
  calmar_ratio REAL,
  win_rate REAL,
  turnover_rate REAL,
  created_at TEXT NOT NULL,
  started_at TEXT NOT NULL,
  finished_at TEXT,
  error_code TEXT,
  error_message TEXT
);
