export interface BuiltInPromptItem {
  id: string;
  category: string;
  market: string[]; // ["CN"], ["US"], ["GLOBAL"]
  title: string;
  prompt: string;
  summary: string;
  tags: string[];
  difficulty?: 'beginner' | 'intermediate' | 'advanced';
  requires_realtime_data?: boolean;
}

export const builtInPrompts: BuiltInPromptItem[] = [
  // 1. 行情诊股 (CN & US)
  {
    id: 'builtin-diag-001',
    category: '行情诊股',
    market: ['CN'],
    title: '诊断 600519.SH 筹码结构与动量分位数',
    prompt: '对贵州茅台 (600519.SH) 进行详细技术面诊断，评估其近60日动量得分、筹码集中度以及相比同行业白酒股的相对强弱。',
    summary: '分析茅台的筹码密集峰、动量强弱及相对同业溢价。',
    tags: ['600519.SH', '动量分位数', '筹码集中度'],
    difficulty: 'beginner',
    requires_realtime_data: true,
  },
  {
    id: 'builtin-diag-002',
    category: '行情诊股',
    market: ['CN'],
    title: '宁德时代 (300750.SZ) 机构资金流与技术阻力位',
    prompt: '诊断宁德时代 (300750.SZ) 最近 30 个交易日的主力资金流向、机构持仓变动预估以及上方 200 日均线压制位。',
    summary: '评估宁德时代主力吸筹力度、换手率突变与压力区间。',
    tags: ['300750.SZ', '主力资金', '技术阻力位'],
    difficulty: 'intermediate',
    requires_realtime_data: true,
  },
  {
    id: 'builtin-diag-003',
    category: '行情诊股',
    market: ['US'],
    title: 'NVIDIA (NVDA.O) 日内波幅与期权隐含波动率',
    prompt: '诊断英伟达 (NVDA) 最新交易日的已实现波动率与期权 IV Skew，评估其财报公布前的市场预期定价。',
    summary: '剖析 NVDA 期权隐含波动率与买卖盘失衡度。',
    tags: ['NVDA', '期权IV', '已实现波动率'],
    difficulty: 'advanced',
    requires_realtime_data: true,
  },
  {
    id: 'builtin-diag-004',
    category: '行情诊股',
    market: ['CN'],
    title: '东方财富 (300059.SZ) 券商 Beta 弹性与成交量归因',
    prompt: '诊断东方财富 (300059.SZ) 在大盘日成交额突破 1.5 万亿时的 Beta 弹性系数、换手率放大倍数与动量延续性。',
    summary: '评估东财在大盘放量行情下的超额弹性和筹码结构。',
    tags: ['300059.SZ', 'Beta弹性', '成交量归因'],
    difficulty: 'intermediate',
    requires_realtime_data: true,
  },
  {
    id: 'builtin-diag-005',
    category: '行情诊股',
    market: ['US'],
    title: 'Tesla (TSLA.O) 交付量公告后的动量与反转特征',
    prompt: '评估特斯拉 (TSLA) 在交付数据发布后 5 个交易日内的动量跳空与均值回归概率。',
    summary: '分析 TSLA 消息面冲击下的量价缺口与反转信号。',
    tags: ['TSLA', '跳空缺口', '均值回归'],
    difficulty: 'intermediate',
    requires_realtime_data: true,
  },
  {
    id: 'builtin-diag-006',
    category: '行情诊股',
    market: ['CN'],
    title: '比亚迪 (002594.SZ) 出口月度数据与动量拐点',
    prompt: '诊断比亚迪 (002594.SZ) 月度海外交付量公布后的股价动量反应，计算其与新能源汽车指数的协方差。',
    summary: '结合新能源车销量归因 BYD 动量拐点。',
    tags: ['002594.SZ', '月度交付量', '动量拐点'],
    difficulty: 'beginner',
    requires_realtime_data: true,
  },
  {
    id: 'builtin-diag-007',
    category: '行情诊股',
    market: ['CN'],
    title: '招商银行 (600036.SH) 资产质量与高股息估值安全边际',
    prompt: '对招商银行 (600036.SH) 进行估值安全边际诊断，结合 PB-ROE 曲线与股息率分位数评估其红利价值。',
    summary: '剖析招行 PB-ROE 安全边际与高股息避险价值。',
    tags: ['600036.SH', 'PB-ROE', '股息率分位数'],
    difficulty: 'intermediate',
    requires_realtime_data: true,
  },
  {
    id: 'builtin-diag-008',
    category: '行情诊股',
    market: ['US'],
    title: 'Apple (AAPL.O) Apple Intelligence 落地与供应链动量',
    prompt: '评估苹果公司 (AAPL) 市盈率 TTM 分位数，以及 Apple Intelligence 功能发布对硬件供应链股票的传导效应。',
    summary: '分析 AAPL 市盈率分位数与 AI 硬件供应链动量。',
    tags: ['AAPL', 'PE-TTM', '供应链传导'],
    difficulty: 'intermediate',
    requires_realtime_data: true,
  },
  {
    id: 'builtin-diag-009',
    category: '行情诊股',
    market: ['CN'],
    title: '工业富联 (601138.SH) AI 服务器代工估值弹性',
    prompt: '诊断工业富联 (601138.SH) 近 60 日的主力筹码密集区，评估其 AI 服务器业务营收占比提升下的动量效应。',
    summary: '评估工业富联筹码分布与 AI 算力硬件代工溢价。',
    tags: ['601138.SH', 'AI服务器', '筹码密集区'],
    difficulty: 'beginner',
    requires_realtime_data: true,
  },
  {
    id: 'builtin-diag-010',
    category: '行情诊股',
    market: ['CN'],
    title: '中芯国际 (688981.SH) 晶圆代工产能与成交量突破',
    prompt: '诊断中芯国际 (688981.SH) 最近 20 个交易日的量价突破信号，计算其与半导体 ETF (512480) 的 Alpha 收益。',
    summary: '量化分析中芯国际量价突破与半导体板块 Alpha。',
    tags: ['688981.SH', '量价突破', 'Alpha收益'],
    difficulty: 'intermediate',
    requires_realtime_data: true,
  },

  // 2. 因子选股 (CN & US)
  {
    id: 'builtin-factor-001',
    category: '因子选股',
    market: ['CN'],
    title: '沪深300高动量低波动精选选股',
    prompt: '从沪深300中筛选最近60日动量排名前20%、20日已实现波动率较低、且换手率持续改善的股票组合。',
    summary: '结合 60D 动量与 20D 低波构建防御兼备组合。',
    tags: ['沪深300', '高动量', '低波动'],
    difficulty: 'beginner',
    requires_realtime_data: true,
  },
  {
    id: 'builtin-factor-002',
    category: '因子选股',
    market: ['CN'],
    title: '高 ROE + 自由现金流收益率 (FCF Yield) 价值质量选股',
    prompt: '筛选全市场 ROE > 18%、自由现金流收益率 FCF Yield 排名前 15%、且连续三年净利润现金含量高于 100% 的标的。',
    summary: '挖掘盈利能力强且现金充沛的优质白马股。',
    tags: ['ROE', 'FCF Yield', '质量因子'],
    difficulty: 'intermediate',
    requires_realtime_data: true,
  },
  {
    id: 'builtin-factor-003',
    category: '因子选股',
    market: ['CN'],
    title: '中证500特异波动率低买选股',
    prompt: '从中证500成分股中剔除特异波动率最高 20% 的标的，挑选 Fama-French 三因子残差方差处于历史低分位的股票。',
    summary: '利用低特异波动率 (IVOL) 捕获超额 Alpha。',
    tags: ['中证500', '特异波动率', 'IVOL'],
    difficulty: 'advanced',
    requires_realtime_data: true,
  },
  {
    id: 'builtin-factor-004',
    category: '因子选股',
    market: ['CN'],
    title: '高股息红利 + 换手率萎缩地量防守选股',
    prompt: '筛选股息率 > 5%、PB < 1.2，且最近 5 个交易日日均换手率处于近一年最低 10% 悬崖区间的地量防御股。',
    summary: '锁定高股息且无虚增博弈的低换手红利防御股。',
    tags: ['高股息', '低换手', '红利防御'],
    difficulty: 'beginner',
    requires_realtime_data: true,
  },
  {
    id: 'builtin-factor-005',
    category: '因子选股',
    market: ['US'],
    title: 'S&P 500 高研发强度 (R&D Ratio) 科技阿尔法选股',
    prompt: '从标普500中筛选研发费用占营业收入比重 > 15%，且近 3 个月一致预期 EPS 上修幅度的科技公司。',
    summary: '筛选研发投入高且分析师业绩上修的科技阿尔法标的。',
    tags: ['S&P500', '研发强度', 'EPS上修'],
    difficulty: 'intermediate',
    requires_realtime_data: true,
  },
  {
    id: 'builtin-factor-006',
    category: '因子选股',
    market: ['CN'],
    title: '分析师目标价上修 (Target Price Upside) 选股',
    prompt: '构建基于“一致预期目标价比率”的选股策略，筛选券商一致目标价高于当前股价 30% 以上且机构覆盖数 > 5 的标的。',
    summary: '捕获分析师看好且上涨空间巨大的蓄势标的。',
    tags: ['目标价空间', '一致预期', '卖方覆盖'],
    difficulty: 'intermediate',
    requires_realtime_data: true,
  },
  {
    id: 'builtin-factor-007',
    category: '因子选股',
    market: ['CN'],
    title: '净资产收益率预期差 (ROE Surprise) 弹性选股',
    prompt: '筛选最新季报实际 ROE 显著超过卖方一致预期 2 个百分点以上、且公布后股价前 3 日出现大单净买入的个股。',
    summary: '挖掘盈利大幅超预期的弹性业绩黑马。',
    tags: ['ROE Surprise', '业绩超预期', '机构买入'],
    difficulty: 'intermediate',
    requires_realtime_data: true,
  },
  {
    id: 'builtin-factor-008',
    category: '因子选股',
    market: ['CN'],
    title: '高 ROIC + 债务比率极低防守质量选股',
    prompt: '筛选投入资本回报率 ROIC > 15%、资产负债率 < 35%，且过去三年营收复合增速 > 10% 的优质民营企业。',
    summary: '严选低负债高回报的稳健增长资本高手。',
    tags: ['ROIC', '低负债', '稳健增长'],
    difficulty: 'intermediate',
    requires_realtime_data: true,
  },
  {
    id: 'builtin-factor-009',
    category: '因子选股',
    market: ['CN'],
    title: '经营现金流与营业收入比 (CFO/Revenue) 现金牛选股',
    prompt: '筛选全市场 CFO/Revenue > 25%、且连续 12 个季度经营现金流净额高于净利润的坚固企业。',
    summary: '排除纸面富贵，精准筛选现金流极强的高质量企业。',
    tags: ['CFO/Revenue', '现金流', '质量因子'],
    difficulty: 'intermediate',
    requires_realtime_data: true,
  },
  {
    id: 'builtin-factor-010',
    category: '因子选股',
    market: ['US'],
    title: 'Nasdaq 100 自由现金流收益率 + 低 Beta 组合',
    prompt: '从纳斯达克100池中剔除 Beta > 1.3 的高波动标的，筛选 FCF Yield 最优的 15 只硬科技防御股票。',
    summary: '降低美股科技头寸波动，构建高 FCF 避险科技阵列。',
    tags: ['Nasdaq100', '低Beta', 'FCF Yield'],
    difficulty: 'intermediate',
    requires_realtime_data: true,
  },

  // 3. 财报拆解 (CN & US)
  {
    id: 'builtin-fin-001',
    category: '财报拆解',
    market: ['US'],
    title: 'NVIDIA (NVDA.O) Data Center 算力与 Blackwell 毛利率拆解',
    prompt: '深度拆解 NVIDIA 最新财报中的 Data Center 业务营收同比增速、Blackwell 架构芯片毛利率与 CapEx 预付现金流。',
    summary: '剖析 NVDA 数据中心算力爆发力与毛利率走势。',
    tags: ['NVDA', 'DataCenter', '毛利率拆解'],
    difficulty: 'intermediate',
    requires_realtime_data: true,
  },
  {
    id: 'builtin-fin-002',
    category: '财报拆解',
    market: ['CN'],
    title: '贵州茅台 (600519.SH) 直销渠道占比与经营现金流剖析',
    prompt: '剖析贵州茅台最新年报中“i 茅台”及直销渠道收入占比变动，评估其对公司综合毛利率与经营性现金流净额的边际拉动。',
    summary: '拆解茅台直销比重提升带来的盈利质量与现金流。',
    tags: ['600519.SH', 'i茅台', '直销渠道占比'],
    difficulty: 'intermediate',
    requires_realtime_data: true,
  },
  {
    id: 'builtin-fin-003',
    category: '财报拆解',
    market: ['US'],
    title: 'Microsoft (MSFT.O) Azure AI 算力与 Copilot 订阅渗透拆解',
    prompt: '拆解微软 (MSFT) 财报中 Intelligent Cloud 部门增速，重点评估 Azure AI 业务拉动效应与 Copilot 商业化收入。',
    summary: '量化 MSFT Azure 云端 AI 收入贡献与商业化渗透。',
    tags: ['MSFT', 'Azure AI', 'Copilot订阅'],
    difficulty: 'intermediate',
    requires_realtime_data: true,
  },
  {
    id: 'builtin-fin-004',
    category: '财报拆解',
    market: ['US'],
    title: 'Tesla (TSLA.O) Energy 储能业务毛利与 FSD 递延收入拆解',
    prompt: '深度拆解特斯拉最新财报，对比汽车销售毛利率与 Megapack 储能业务营收增速及 FSD 软件许可递延收入确认。',
    summary: '剖析特斯拉储能增长第二曲线与软件毛利润。',
    tags: ['TSLA', '储能业务', 'FSD递延收入'],
    difficulty: 'intermediate',
    requires_realtime_data: true,
  },
  {
    id: 'builtin-fin-005',
    category: '财报拆解',
    market: ['CN'],
    title: '中芯国际 (688981.SH) 晶圆出货量、ASP 均价与 CapEx 资本开支',
    prompt: '拆解中芯国际最新季报，分析 8 英寸与 12 英寸晶圆产能利用率、平均售价 ASP 变动及 2026 年 CapEx 规划。',
    summary: '评估中芯国际产能利用率与先进制程 CapEx。',
    tags: ['688981.SH', '晶圆代工', 'CapEx'],
    difficulty: 'intermediate',
    requires_realtime_data: true,
  },
  {
    id: 'builtin-fin-006',
    category: '财报拆解',
    market: ['US'],
    title: 'AMD (AMD.O) MI300 GPU 交付与 Data Center 市场份额',
    prompt: '解析 AMD 最新财报，重点评估 MI300X/MI325 系列 GPU 销售额指引与在 AI 算力芯片市场的份额变动。',
    summary: '追踪 AMD MI300 系列 GPU 增长潜力与 Data Center 毛利。',
    tags: ['AMD', 'MI300X', 'AI算力芯片'],
    difficulty: 'intermediate',
    requires_realtime_data: true,
  },
  {
    id: 'builtin-fin-007',
    category: '财报拆解',
    market: ['CN'],
    title: '宁德时代 (300750.SZ) 动力电池单位 Wh 净利润与海外产能',
    prompt: '拆解宁德时代最新财报，计算每瓦时 (Wh) 动力电池与储能电池的净利润变动，评估欧洲工厂产能落地收益。',
    summary: '量化宁德时代单 Wh 盈利稳定性与海外市场表现。',
    tags: ['300750.SZ', '单Wh净利', '储能电池'],
    difficulty: 'intermediate',
    requires_realtime_data: true,
  },

  // 4. 策略构建 (CN & US)
  {
    id: 'builtin-strat-001',
    category: '策略构建',
    market: ['CN'],
    title: '质量成长 ROE + 自由现金流多因子调仓模型',
    prompt: '请设计一套基于“ROE 稳定度 + 自由现金流收益率 + 60日动量”的 A 股质量成长多因子量化策略，给出因子权重配置与每周调仓逻辑。',
    summary: '设计高 ROE 与高现金流的多因子周度调仓策略。',
    tags: ['多因子', '周度调仓', '质量成长'],
    difficulty: 'intermediate',
    requires_realtime_data: false,
  },
  {
    id: 'builtin-strat-002',
    category: '策略构建',
    market: ['CN'],
    title: 'CTA 肯特纳通道 (Keltner Channel) 真实波幅突破策略',
    prompt: '编写基于 Keltner Channel 结合 20D ATR 动态止损的商品/股指期货趋势跟踪策略，制定多空建仓与出场规则。',
    summary: '构建肯特纳通道结合 ATR 动态止损的趋势跟踪系统。',
    tags: ['CTA', 'KeltnerChannel', 'ATR止损'],
    difficulty: 'intermediate',
    requires_realtime_data: false,
  },
  {
    id: 'builtin-strat-003',
    category: '策略构建',
    market: ['CN'],
    title: '网格交易与 20 日均线动量过滤器结合策略',
    prompt: '请设计一套网格交易策略，加入 20 日指数移动平均线 (EMA) 趋势方向作为上游过滤器，防止单边下跌市场爆仓。',
    summary: '结合 EMA20 趋势过滤器的防暴仓网格交易系统。',
    tags: ['网格交易', 'EMA过滤器', '风险控制'],
    difficulty: 'intermediate',
    requires_realtime_data: false,
  },
  {
    id: 'builtin-strat-004',
    category: '策略构建',
    market: ['CN'],
    title: 'Barra 风格因子中性化与股指期货 Alpha 对冲组合',
    prompt: '构建一个包含 30 只股票的行业中性与市值中性 Alpha 多头组合，使用沪深 300 股指期货 (IF) 执行精准对冲。',
    summary: '设计行业与市值双重中性的纯超额 Alpha 对冲策略。',
    tags: ['Barra', '中性化', '股指期货对冲'],
    difficulty: 'advanced',
    requires_realtime_data: false,
  },
  {
    id: 'builtin-strat-005',
    category: '策略构建',
    market: ['GLOBAL'],
    title: '双重动量 (Dual Momentum) 绝对与相对动量轮动',
    prompt: '阐述 Gary Antonacci 的双重动量策略，结合标的自身过去 12 个月绝对正收益过滤与同类资产相对超额排名进行自动仓位切换。',
    summary: '构建融合绝对收益门槛与相对强弱排名的双动量策略。',
    tags: ['DualMomentum', '绝对动量', '资产轮动'],
    difficulty: 'intermediate',
    requires_realtime_data: false,
  },
  {
    id: 'builtin-strat-006',
    category: '策略构建',
    market: ['CN'],
    title: '结合 RSRS (阻力支撑相对强度) 的大盘择时系统',
    prompt: '设计一套基于 RSRS 斜率指标与标准分 Z-Score 的大盘仓位择时模型，详细计算支撑位与阻力位拟合 R2。',
    summary: '使用 RSRS 支撑阻力斜率 Z-Score 实现动态大盘仓位管理。',
    tags: ['RSRS', '大盘择时', 'Z-Score'],
    difficulty: 'advanced',
    requires_realtime_data: false,
  },

  // 5. 策略回测 (CN & US)
  {
    id: 'builtin-backtest-001',
    category: '策略回测',
    market: ['CN'],
    title: 'A股 T+1、滑点与印花税约束下的多因子回测',
    prompt: '在严格遵守 A 股 T+1 制度、0.05% 印花税与双边 0.05% 滑点假设下，评估中证500成分股周度调仓策略在 2021-2025 年的最大回撤与夏普比率。',
    summary: '带严格 A 股交易摩擦参数的多因子回测实验。',
    tags: ['T+1', '交易摩擦', '夏普比率'],
    difficulty: 'intermediate',
    requires_realtime_data: false,
  },
  {
    id: 'builtin-backtest-002',
    category: '策略回测',
    market: ['CN'],
    title: '多因子截面 Rank 多头五分位组合回测与多空收益差',
    prompt: '编写代码计算多因子在全市场截面上的 Top 20% 多头五分位数与 Bottom 20% 空头组合的多空对冲年化收益率与胜率。',
    summary: '对多因子进行五分位多空对冲组合历史表现测试。',
    tags: ['五分位回测', '多空对冲', 'RankIC'],
    difficulty: 'intermediate',
    requires_realtime_data: false,
  },
  {
    id: 'builtin-backtest-003',
    category: '策略回测',
    market: ['US'],
    title: '标普500 成分股月度再平衡 (Rebalancing) 回测',
    prompt: '对基于标普500成分股等权重月度调仓策略进行 10 年历史回测，对比市值加权标普500 (SPY) 的超额收益与跟踪误差。',
    summary: '对比等权重标普500与 SPY 市值加权的超额回测。',
    tags: ['S&P500', '等权重', '跟踪误差'],
    difficulty: 'beginner',
    requires_realtime_data: false,
  },

  // 6. 宏观轮动 (CN & US & GLOBAL)
  {
    id: 'builtin-macro-001',
    category: '宏观轮动',
    market: ['CN'],
    title: '高股息红利低波与半导体科技股宏观轮动',
    prompt: '结合当前十年期国债收益率与全市场流动性，评估高股息红利股 (中证红利) 与半导体科技股 (芯片 ETF) 的配置胜率与轮动逻辑。',
    summary: '根据无风险利率与流动性，构建红利与科技资产轮动框架。',
    tags: ['红利低波', '半导体', '国债收益率'],
    difficulty: 'intermediate',
    requires_realtime_data: true,
  },
  {
    id: 'builtin-macro-002',
    category: '宏观轮动',
    market: ['GLOBAL'],
    title: '美联储降息通道下纳斯达克100与黄金 (GLD) 轮动',
    prompt: '分析美联储降息周期中纳斯达克100指数与黄金 ETF (GLD) 的比价效应，建立基于动量差值的跨资产配置模型。',
    summary: '评估美联储利率决议下科技股与黄金的比价轮动。',
    tags: ['美联储降息', '纳斯达克100', '黄金GLD'],
    difficulty: 'intermediate',
    requires_realtime_data: true,
  },
  {
    id: 'builtin-macro-003',
    category: '宏观轮动',
    market: ['CN'],
    title: 'PPI-CPI 通胀剪刀差与中下游制造业利润修复',
    prompt: '建模 PPI-CPI 通胀剪刀差变动对 A 股中下游机械设备与新能源制造行业相比上游资源品行业相对超额收益的回归显著性。',
    summary: '通过通胀剪刀差评估中下游制造业与上游采掘板块相对收益。',
    tags: ['PPI-CPI', '通胀剪刀差', '制造业利润'],
    difficulty: 'advanced',
    requires_realtime_data: true,
  },

  // 7. 行业研究 (CN & US)
  {
    id: 'builtin-ind-001',
    category: '行业研究',
    market: ['CN'],
    title: '白酒行业渠道库存与动量动向研究',
    prompt: '分析白酒行业头部企业（茅台、五粮液、泸州老窖）的渠道批价变动、库存周转天数以及多因子排序中的 Alpha 表现。',
    summary: '结合白酒批价与库存周转率构建行业超额选股逻辑。',
    tags: ['白酒行业', '渠道批价', '库存周转'],
    difficulty: 'intermediate',
    requires_realtime_data: true,
  },
  {
    id: 'builtin-ind-002',
    category: '行业研究',
    market: ['US'],
    title: '全球半导体晶圆代工与设备链周期轮动',
    prompt: '比较台积电 (TSM)、阿斯麦 (ASML) 与应用材料 (AMAT) 的订单交付周期、CapEx 资本开支及对半导体 ETF (SOXX) 的引领作用。',
    summary: '剖析全球半导体设备链订单周期与美股科技板块映射。',
    tags: ['ASML', 'TSM', '半导体周期'],
    difficulty: 'intermediate',
    requires_realtime_data: true,
  },

  // 8. 组合管理 (CN & US)
  {
    id: 'builtin-port-001',
    category: '组合管理',
    market: ['GLOBAL'],
    title: '风险平价 (Risk Parity) 多资产权重配置模型',
    prompt: '基于股票、债券与黄金构建风险平价资产组合，详细推导各资产在组合中的边际风险贡献 (MRC) 均衡方程。',
    summary: '推导并实现使股票/债券/黄金边际风险贡献相等的风险平价算法。',
    tags: ['RiskParity', '边际风险', '资产配置'],
    difficulty: 'advanced',
    requires_realtime_data: false,
  },
  {
    id: 'builtin-port-002',
    category: '组合管理',
    market: ['CN'],
    title: '黑-利特曼 (Black-Litterman) 主观观点融合组合优化',
    prompt: '阐述如何使用 Black-Litterman 模型将量化研究员对行业或个股的主观预期 (Views) 融合到市场均衡收益率中，优化投资组合权重。',
    summary: '将主观预期与市场均衡收益相结合的 BL 组合优化模型。',
    tags: ['Black-Litterman', '主观观点', '组合优化'],
    difficulty: 'advanced',
    requires_realtime_data: false,
  },

  // 9. 风险分析 (CN & US)
  {
    id: 'builtin-risk-001',
    category: '风险分析',
    market: ['CN'],
    title: '持仓组合在 95% 置信度下的 Value at Risk (VaR) 计算',
    prompt: '对包含 15 只 A 股股票的持仓组合，采用蒙特卡洛模拟法与历史模拟法分别计算其在 95% 置信度下 10 日持有的 VaR 风险值。',
    summary: '对比蒙特卡洛与历史模拟法在组合 VaR 计算中的差异。',
    tags: ['VaR', '蒙特卡洛', '风险控制'],
    difficulty: 'intermediate',
    requires_realtime_data: false,
  },
  {
    id: 'builtin-risk-002',
    category: '风险分析',
    market: ['CN'],
    title: '行业集中度与单一个股最大回撤风险归因',
    prompt: '对多因子策略的持仓矩阵进行离散度与集中度分析，计算赫芬达尔指数 (HHI) 及前三大持仓对总投资组合回撤的贡献度。',
    summary: '归因持仓集中度 HHI 与个股爆雷风险。',
    tags: ['HHI集中度', '风险归因', '最大回撤'],
    difficulty: 'intermediate',
    requires_realtime_data: false,
  },

  // 10. 事件研究 (CN & US)
  {
    id: 'builtin-event-001',
    category: '事件研究',
    market: ['CN'],
    title: '股票回购公告后的累计超额收益 (CAR) 事件研究',
    prompt: '采用事件研究法 (Event Study) 分析上市公司发布大额股份回购方案后 [-5, +30] 个交易日内股票的累计超额收益率 (CAR)。',
    summary: '量化上市公司回购公告公布后的事件驱动 Alpha。',
    tags: ['股份回购', '事件研究', 'CAR超额收益'],
    difficulty: 'advanced',
    requires_realtime_data: false,
  },
  {
    id: 'builtin-event-002',
    category: '事件研究',
    market: ['CN'],
    title: '高管增持与大股东减持离场信号事件驱动',
    prompt: '分析核心高管通过二级市场增持股份超过 1000 万元公告后，股票在 60 个交易日内的动量延续性与胜率分布。',
    summary: '检验内部高管真金白银增持的强多头信号效应。',
    tags: ['高管增持', '事件驱动', '胜率分布'],
    difficulty: 'intermediate',
    requires_realtime_data: false,
  },

  // 11. A股研究 (CN)
  {
    id: 'builtin-cn-001',
    category: 'A股研究',
    market: ['CN'],
    title: '北向资金/外资大额买入标的跟踪与超额收益',
    prompt: '量化评估沪深股通北向资金连续 5 个交易日净买入额超过 5 亿元标的的短期跟风超额收益。',
    summary: '分析北向资金流向与 A 股核心资产收益相关性。',
    tags: ['北向资金', '沪深股通', '资金流向'],
    difficulty: 'beginner',
    requires_realtime_data: true,
  },
  {
    id: 'builtin-cn-002',
    category: 'A股研究',
    market: ['CN'],
    title: '科创50成分股芯片硬件研发投入与估值溢价',
    prompt: '评估科创50指数成分股的 PS-TTM 估值与研发费用率的相关性，筛选研发转化为营收能力最强的硬科技公司。',
    summary: '挖掘科创板高研发转化效率的硬科技龙头。',
    tags: ['科创50', '研发转化率', 'PS估值'],
    difficulty: 'intermediate',
    requires_realtime_data: true,
  },

  // 12. 美股研究 (US)
  {
    id: 'builtin-us-001',
    category: '美股研究',
    market: ['US'],
    title: '美股七巨头 (Magnificent 7) 盈利集中度与估值分位数',
    prompt: '计算美股七巨头 (NVDA, MSFT, AAPL, AMZN, GOOGL, META, TSLA) 在标普500总市值中的占比及其远期市盈率 PEG 矩阵。',
    summary: '分析美股科技七巨头的权重集中度与 PEG 估值。',
    tags: ['美股七巨头', 'PEG估值', '标普500'],
    difficulty: 'beginner',
    requires_realtime_data: true,
  },
  {
    id: 'builtin-us-002',
    category: '美股研究',
    market: ['US'],
    title: '标普500 13F 机构大鳄仓位重合度与动量分析',
    prompt: '基于最新 13F 季度持仓披露，提取顶级对冲基金（如 Citadel, Bridgewater）共同加仓前 10 名的美股标的组合。',
    summary: '追踪 13F 机构对冲基金加仓重合度最高的共识标的。',
    tags: ['13F', '对冲基金', '机构持仓'],
    difficulty: 'intermediate',
    requires_realtime_data: true,
  },

  // 13. 跨市场研究 (GLOBAL)
  {
    id: 'builtin-global-001',
    category: '跨市场研究',
    market: ['GLOBAL'],
    title: 'AH 股溢价率 2 倍标准差统计套利模型',
    prompt: '分析 AH 股溢价指数历史走势，建立基于 A/H 股价偏离历史均值 2 倍标准差时的配对交易套利与对冲逻辑。',
    summary: '针对同股同权的 AH 股溢价进行均值回归统计套利。',
    tags: ['AH股溢价', '配对套利', '均值回归'],
    difficulty: 'intermediate',
    requires_realtime_data: true,
  },
  {
    id: 'builtin-global-002',
    category: '跨市场研究',
    market: ['GLOBAL'],
    title: '中美十年期国债利差与跨境资本动量归因',
    prompt: '建模中美十年期国债利差变动对离岸人民币汇率 (USD/CNH) 及北向资金流向的敏感性系数。',
    summary: '分析中美利差变动对汇率与跨境资本动量的传导。',
    tags: ['中美利差', '离岸人民币', '资本流向'],
    difficulty: 'advanced',
    requires_realtime_data: true,
  },

  // 14. AI / ML (GLOBAL)
  {
    id: 'builtin-aiml-001',
    category: 'AI / ML',
    market: ['GLOBAL'],
    title: 'LightGBM 梯度提升树预测多因子截面收益率',
    prompt: '解释使用 LightGBM 模型对 20 个基本面与技术面因子进行训练时的超参数调优（学习率、树深度、Feature Fraction）与交叉验证流程。',
    summary: '构建 LightGBM 梯度提升树预测股票截面超额收益。',
    tags: ['LightGBM', '机器学习', '截面预测'],
    difficulty: 'advanced',
    requires_realtime_data: false,
  },
  {
    id: 'builtin-aiml-002',
    category: 'AI / ML',
    market: ['GLOBAL'],
    title: 'Transformer / PatchTST 架构高频 K 线特征提取',
    prompt: '探讨采用 PatchTST 深度学习模型处理分钟级高频 K 线序列并预测突破概率的算力需求与特征归一化技巧。',
    summary: '使用 PatchTST 深度神经网络建模高频 K 线序列突破。',
    tags: ['Transformer', 'PatchTST', '高频突破'],
    difficulty: 'advanced',
    requires_realtime_data: false,
  },
  {
    id: 'builtin-aiml-003',
    category: 'AI / ML',
    market: ['GLOBAL'],
    title: '强化学习 PPO 算法自动量化交易 Agent 状态空间设计',
    prompt: '设计一套基于 PPO (Proximal Policy Optimization) 的深度强化学习交易 Agent，定义其状态空间 State、动作空间 Action 与奖励函数 Reward。',
    summary: '设计 PPO 强化学习量化 Agent 的状态、动作与 Reward 函数。',
    tags: ['强化学习', 'PPO', '自动交易Agent'],
    difficulty: 'advanced',
    requires_realtime_data: false,
  },

  // 15. 数据分析 (CN & US)
  {
    id: 'builtin-data-001',
    category: '数据分析',
    market: ['CN'],
    title: 'AKShare 日频行情数据清洗与异常值 MAD 过滤',
    prompt: '编写 Python 数据清洗脚本，提取 AKShare 日频行情中的停牌股、一字涨跌停标的并采用 MAD 算法过滤极值。',
    summary: '实现专业的金融数据清洗流，剔除停牌与涨跌停噪音。',
    tags: ['AKShare', '数据清洗', 'MAD过滤'],
    difficulty: 'beginner',
    requires_realtime_data: false,
  },
  {
    id: 'builtin-data-002',
    category: '数据分析',
    market: ['CN'],
    title: 'Level-2 逐笔委托买卖队列失衡度 (Order Imbalance)',
    prompt: '详细说明如何利用 Level-2 五档买卖挂单量计算订单簿失衡度 (Order Imbalance)，并建立 5 分钟短线价格预测模型。',
    summary: '利用 Level-2 深度挂单数据计算订单失衡度并预测极短线走势。',
    tags: ['Level-2', '订单失衡度', '高频数据'],
    difficulty: 'advanced',
    requires_realtime_data: false,
  },

  // 16. 因子研究 (CN & US)
  {
    id: 'builtin-facres-001',
    category: '因子研究',
    market: ['CN'],
    title: '施加 Gram-Schmidt 过程进行因子正交化清洗',
    prompt: '详细说明如何利用 Gram-Schmidt 过程或对称正交化法消除动量因子与波动率因子之间的共线性，保留纯粹的 Alpha 残差。',
    summary: '采用 Gram-Schmidt 过程消除强相关因子间多重共线性。',
    tags: ['因子正交化', 'Gram-Schmidt', '共线性清洗'],
    difficulty: 'advanced',
    requires_realtime_data: false,
  },
  {
    id: 'builtin-facres-002',
    category: '因子研究',
    market: ['CN'],
    title: '多因子 RankIC 20D 衰减速度计算与调仓周期决策',
    prompt: '如何测量多因子模型在 1D / 5D / 10D / 20D 调仓周期下的 RankIC 衰减半衰期，以确定最优调仓频率。',
    summary: '计算因子 RankIC 半衰期曲线以优化策略调仓频率。',
    tags: ['RankIC衰减', '半衰期', '调仓频率'],
    difficulty: 'intermediate',
    requires_realtime_data: false,
  },

  // 17. 异常检测 (CN & US)
  {
    id: 'builtin-anom-001',
    category: '异常检测',
    market: ['CN'],
    title: '全市场换手率突变 3 倍与成交量异常检测',
    prompt: '设计一套日频异常放量监测算法，筛选当日换手率达到近 20 日均值 3 倍以上且伴随均线向上突破的潜在黑马股。',
    summary: '监测换手率与成交量异动，识别主力试盘与资金突破。',
    tags: ['换手率异动', '成交量突变', '黑马检测'],
    difficulty: 'intermediate',
    requires_realtime_data: true,
  },
  {
    id: 'builtin-anom-002',
    category: '异常检测',
    market: ['CN'],
    title: '尾盘 15 分钟跳水与主力诱多拉升特征检测',
    prompt: '分析股票在 14:45 分之后成交量骤增但价格急跌的尾盘跳水特征，构建防范诱多挂单与闪崩的警报规则。',
    summary: '检测尾盘异动与异常砸盘，构建防诱多防闪崩警报。',
    tags: ['尾盘异动', '闪崩预警', '主力行为'],
    difficulty: 'intermediate',
    requires_realtime_data: true,
  },
];
